"""add watchlist

Revision ID: 455fbdec884a
Revises: c614331d7191
Create Date: 2023-03-28 04:38:00.759812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '455fbdec884a'
down_revision = 'c614331d7191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('watchlist', sa.JSON(), nullable=True))
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('watchlist')

    # ### end Alembic commands ###
